name: Backend Static Check

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - "release/*.*.*"

jobs:
  go-static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
          cache: true
      - name: Verify go.mod is tidy
        run: |
          go mod tidy -go=1.21
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          args: --verbose --timeout=3m
          skip-cache: true
